# Generated by Django 4.1.7 on 2023-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('img_url', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=30)),
                ('ram', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
